### ISSUE TITLE
Basic EDD pagination styling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#50]
I am aware a lot of small stuff like this is best left up to child themes, but I honestly feel at least some basic styling should be included for EDD pagination on the download shortcode/archive pages to make it easier to navigate. At the minute it's just a plain textual link which is difficult to click/use.

**Comment by amdrew** [comment]
👍 I agree, it's pretty bland and should at least have something simple

**Comment by amdrew** [comment]
Added some basic pagination:

![screen shot 2017-06-26 at 8 29 59 pm](https://user-images.githubusercontent.com/52581/27530779-43e8e452-5aae-11e7-8934-1812c3702a5b.png)

**Comment by davidsherlock** [comment]
Looking good @amdrew, however more importantly is this a new direction I see for the product boxes? Would be awesome if that price button opened up a drawer for variable priced products so purchases could be made on the archive pages.

**Comment by amdrew** [comment]
@davidsherlock No new direction, I just like to test out some alternate styling every now and again to see how everything looks together. I also like to make sure all the necessary HTML is in place so specific elements can be styled. The boxed look might be something a child theme would like to implement.

> Would be awesome if that price button opened up a drawer for variable priced products so purchases could be made on the archive pages.

Neat idea for a child theme 😄

**Comment by davidsherlock** [comment]
@amdrew, for quickness could you post the styling/changes you made here so I can test them out? I prefer the new look you went for here :)

**Comment by davidsherlock** [comment]
I would also recommend adding the pagination styling to other areas, such as FES dashboard (product list, comments, etc.) to keep consistency across the theme.

**Comment by davidsherlock** [comment]
Also a suggestion for the pagination, it would be useful if the customizer "button" styling applied to the active and hovers.

**Comment by amdrew** [comment]
> I would also recommend adding the pagination styling to other areas, such as FES dashboard (product list, comments, etc.) to keep consistency across the theme.

Absolutely, will do that

> Also a suggestion for the pagination, it would be useful if the customizer "button" styling applied to the active and hovers.

I did think about that. I decided it's not really a button as a customer would expect. The might style the buttons to their liking and not want the same styling applied to the pagination. I'm going to leave it as-is for now.

> for quickness could you post the styling/changes you made here so I can test them out? I prefer the new look you went for here :)

Sure, tweak as required, it was just something rough:

``` css

.eddDownloadMeta-price {
	background: #eee;
	padding: 0.25rem 0.5rem;
}

.edd_download {
	margin-bottom: 1rem;
}

.edd_download_inner {
	background: #f7f7f7;
	padding: 1rem;
}

@media only screen and (min-width: 768px) {

	.edd_download {
		margin-bottom: 0;
	}

	.edd_download_inner {
		margin: 1rem;
		padding: 1.5rem;
	}

	.edd_downloads_list {
		margin-top: -1rem;
		margin-left: -1rem;
		margin-right: -1rem;
	}

}
```
